services:
  liferay:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      LIFERAY_VIRTUAL_PERIOD_HOSTS_PERIOD_VALID_PERIOD_HOSTS: liferay,localhost,127.0.0.1,[::1],[0:0:0:0:0:0:0:1]
  etc-golang:
    build:
      dockerfile: Dockerfile
      context: etc-golang
    ports:
      - "8126:8126"
    depends_on:
      liferay:
        condition: service_healthy