services:
  liferay:
    build:
      dockerfile: Dockerfile
      context: .
    ports:
      - "8080:8080"
    environment:
      LIFERAY_VIRTUAL_PERIOD_HOSTS_PERIOD_VALID_PERIOD_HOSTS: liferay,localhost,127.0.0.1,[::1],[0:0:0:0:0:0:0:1]
  sample-etc-golang:
    build:
      dockerfile: Dockerfile
      context: sample-etc-golang
    ports:
      - "8126:8126"
    depends_on:
      liferay:
        condition: service_healthy
  sample-etc-python-fastapi:
    build:
      dockerfile: Dockerfile
      context: sample-etc-python-fastapi
    ports:
      - "8502:8502"
    environment:
      PROJECT_PROTOCOL: http
      PROJECT_HOSTNAME: sample-etc-python-fastapi
      PROJECT_PORT: 8502
    depends_on:
      liferay:
        condition: service_healthy
  sample-etc-java-vertx:
    build:
      dockerfile: Dockerfile
      context: sample-etc-java-vertx
    ports:
      - "8082:8082"
    depends_on:
      liferay:
        condition: service_healthy